### ISSUE TITLE
ionic cordova resources

### ISSUE THREAD

**Issue by BigDee123** [fttx/barcode-to-pc-app#132]
i can't run ionic cordova resources it gives me the following errors : 

typescript: C:/barcode-to-pc-app-master/src/app/app.component.ts, line: 28 
            Expected 2 arguments, but got 1. 

      L27:  export class MyApp {
      L28:    @ViewChild('mainMenu') nav: NavController

[09:03:40]  typescript: C:/barcode-to-pc-app-master/src/pages/scan-session/scan-session.ts, line: 35 
            Expected 2 arguments, but got 1.

      L34:  export class ScanSessionPage {
      L35:    @ViewChild('keyboardInput') keyboardInput;

[09:03:40]  typescript: C:/barcode-to-pc-app-master/src/pages/welcome/welcome.ts, line: 26 
            Expected 2 arguments, but got 1.

      L25:  export class WelcomePage {
      L26:    @ViewChild('welcome') slider: Slides;
      L27:    public showNext = true;

[09:03:40]  typescript: C:/barcode-to-pc-app-master/src/providers/scan-sessions-storage.ts, line: 24 
            Property 'debounceTime' does not exist on type 'Subject<ScanSessionModel[]>'.

      L23:  ) {
      L24:    this.onScanSessionSetObservable.debounceTime(500).subscribe((scanSessions: ScanSessionModel[]) => {
      L25:      console.log('saving:', scanSessions)

[09:03:40]  typescript: C:/barcode-to-pc-app-master/src/providers/scan.ts, line: 259 
            Property 'first' does not exist on type 'Observable<BarcodeScanResult>'.

     L258:  if (!barcodesStack) {
     L259:  rcodeScanResult: BarcodeScanResult = await this.barcodeScanner.scan(this.pluginOptions).first().toPromise();
     L260:      if (!barcodeScanResult || barcodeScanResult.cancelled) {

[09:03:40]  ionic-app-script task: "build" 
[09:03:40]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (C:\barcode-to-pc-app-master\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\barcode-to-pc-app-master\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (C:\barcode-to-pc-app-master\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (C:\barcode-to-pc-app-master\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at C:\barcode-to-pc-app-master\node_modules\@ionic\app-scripts\dist\build.js:109:82
[ERROR] An error occurred while running subprocess ionic-app-scripts.

        ionic-app-scripts build --target cordova --platform ios exited with exit code 1.

**Comment by fttx** [comment]
Try to match this ionic and cordova version: https://github.com/fttx/barcode-to-pc-app/blob/master/last-ionic-info.txt

And also this typescritp version: https://github.com/fttx/barcode-to-pc-app/blob/a533ef69b8744482a8fb7550e9bc314bf6d6741e/package.json#L77
